[workspace]
resolver = "2"

members = [
    "crates/souprune",
    "crates/bevy_ecs_typewriter",
    "crates/bevy_fact_rule_event",
    "crates/bevy_mortar_bond"
,
    "crates/souprune_api"
,
    "crates/souprune_sdk"
,
    "crates/souprune_mod_test"
,
    "crates/souprune_mock_host"
]

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1
debug = 1
incremental = true

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
debug = 0

[patch.crates-io]
# Force every workspace crate to use the local mortar compiler implementation.
mortar_compiler = { path = "../mortar/crates/mortar_compiler" }
