//! Snapshot test for the Rust builder output of `cotton_first_turn`.
//!
//! `cotton_first_turn` Rust 构造输出的快照测试。

#[path = "support/cotton_first_turn_assertions.rs"]
mod cotton_first_turn_assertions;
#[path = "../../../projects/example_mod/content/src/performances.rs"]
mod example_mod_content_performances;

use cotton_first_turn_assertions::{assert_same_performance, parse_generated_ron};
use souprune_schema::danmaku::DanmakuPerformance;

#[test]
fn example_mod_performance_builders_are_reachable() {
    let _ = example_mod_content_performances::cotton_top_sweep as fn() -> DanmakuPerformance;
    let _ = example_mod_content_performances::cotton_surround as fn() -> DanmakuPerformance;
    let _ = example_mod_content_performances::cotton_side_pincer as fn() -> DanmakuPerformance;
    let _ = example_mod_content_performances::cotton_bottom_wave as fn() -> DanmakuPerformance;
}

#[test]
fn cotton_first_turn_snapshot() {
    let generated = example_mod_content_performances::cotton_first_turn();
    let original_ron = include_str!(
        "../../../projects/example_mod/battle/danmaku/cotton_first_turn.performance.ron"
    );
    let original: DanmakuPerformance =
        ron::from_str(original_ron).expect("hand-written cotton_first_turn should parse");

    let pretty_config = ron::ser::PrettyConfig::default()
        .struct_names(true)
        .enumerate_arrays(false);
    let generated_ron = ron::ser::to_string_pretty(&generated, pretty_config)
        .expect("generated RON should serialize");
    let generated_round_trip = parse_generated_ron(&format!(
        "// Generated by Vessel — do not edit manually\n{generated_ron}\n"
    ));

    assert_same_performance(&generated_round_trip, &original);
}
