//! End-to-end test for `cotton_first_turn` through a real Vessel guest component.
//!
//! `cotton_first_turn` 通过真实 Vessel guest component 的端到端测试。

#[path = "support/cotton_first_turn_assertions.rs"]
mod cotton_first_turn_assertions;

use cotton_first_turn_assertions::{assert_same_performance, parse_generated_ron};
use souprune_schema::danmaku::DanmakuPerformance;
use std::fs;
use std::path::PathBuf;
use std::process::Command;
use std::time::{SystemTime, UNIX_EPOCH};

#[test]
fn cotton_first_turn_component_build_matches_reference_asset() {
    let fixture_dir =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../projects/example_mod/content");

    let build_status = Command::new("cargo")
        .current_dir(&fixture_dir)
        .args(["build", "--target", "wasm32-wasip2"])
        .status()
        .expect("failed to invoke cargo build for example_mod content guest");
    assert!(
        build_status.success(),
        "example_mod content guest should build successfully"
    );

    let component_path = fixture_dir.join("target/wasm32-wasip2/debug/content.wasm");
    assert!(
        component_path.exists(),
        "example_mod content component should exist"
    );

    let unique = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("system clock should be after unix epoch")
        .as_nanos();
    let output_dir = std::env::temp_dir().join(format!("vessel_cotton_first_turn_{unique}"));
    let _ = fs::remove_dir_all(&output_dir);

    let summary = vessel::build_component(&component_path, &output_dir)
        .expect("vessel host should build cotton_first_turn from the guest component");
    assert_eq!(
        summary.written_files, 6,
        "expected all example_mod performances to be generated"
    );

    let output_path = output_dir.join("battle/danmaku/cotton_first_turn.performance.ron");
    assert!(
        output_path.exists(),
        "generated cotton_first_turn output should exist"
    );

    let generated_ron = fs::read_to_string(&output_path)
        .expect("generated cotton_first_turn output should be readable");
    assert!(
        generated_ron.contains("Generated by Vessel"),
        "generated output should contain the Vessel header"
    );

    let generated = parse_generated_ron(&generated_ron);
    let original_ron = include_str!(
        "../../../projects/example_mod/battle/danmaku/cotton_first_turn.performance.ron"
    );
    let original: DanmakuPerformance =
        ron::from_str(original_ron).expect("reference cotton_first_turn should parse");

    assert_same_performance(&generated, &original);

    let _ = fs::remove_dir_all(&output_dir);
}
