use std::fs;
use std::path::PathBuf;
use std::time::{SystemTime, UNIX_EPOCH};

fn temp_output_dir(prefix: &str) -> PathBuf {
    let unique = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("system clock should be after unix epoch")
        .as_nanos();
    let output_dir = std::env::temp_dir().join(format!("{prefix}_{unique}"));
    let _ = fs::remove_dir_all(&output_dir);
    output_dir
}

#[test]
fn souprune_wrapper_preserves_sparse_semantically_equal_view_body() {
    let output_dir = temp_output_dir("souprune_cauld_ron_semantic_preserve");

    fs::create_dir_all(output_dir.join("battle/view")).expect("should create output directory");
    fs::create_dir_all(output_dir.join(".build")).expect("should create build directory");
    fs::write(
        output_dir.join(".build/cauld-ron-output-manifest.toml"),
        r#"version = 1
owned_paths = ["battle/view/sparse.view.ron"]
"#,
    )
    .expect("should write output manifest");
    fs::write(
        output_dir.join("battle/view/sparse.view.ron"),
        r#"// =============================================================================
// BOOTSTRAPPED BY VESSEL
// =============================================================================
// This file was initially generated by Vessel to provide a baseline structure.
//
// [ MANUAL EDITS ALLOWED - PROCEED WITH CAUTION ]
// You can modify this file to suit your specific needs. However,
// be aware that regenerating this module via Vessel will OVERWRITE this file.
//
// GUIDELINES FOR MODIFICATION:
// 1. SAFETY FIRST: Ensure your current state is committed to version control
//    (e.g., Git) before making changes, so you can easily revert or handle
//    future merge conflicts.
// 2. THE "PROPER" WAY: If your goal is to change the underlying logic or
//    structure globally, please edit the Vessel source schema/configuration
//    instead of modifying this file directly.
// =============================================================================
// Generated at: 2000-01-01 00:00:00 +00:00

(
    roots: [
        (
            name: "Root",
        ),
    ],
    requires: [],
    facts: None,
    world_space: false,
    coordinate_system: Standard,
)
"#,
    )
    .expect("should write sparse existing output");

    souprune_cauld_ron::write_generated_files(
        &[cauld_ron::GeneratedRonFile {
            path: PathBuf::from("battle/view/sparse.view.ron"),
            ron_text: r#"(
    roots: [
        (
            name: "Root",
            tags: [],
            style: (
                width: None,
                height: None,
                left: None,
                right: None,
                top: None,
                bottom: None,
                position_type: None,
                flex_direction: None,
                justify_content: None,
                align_items: None,
            ),
            visible_when: None,
            background_color: None,
            border_color: None,
            image: None,
            sprite: None,
            state_sprite: None,
            texts: [],
            view_box: None,
            children: [],
            repeat: None,
        ),
    ],
    requires: [],
    facts: None,
    world_space: false,
    coordinate_system: Standard,
)
"#
            .to_owned(),
        }],
        &output_dir,
    )
    .expect("semantically equal output should refresh timestamp through souprune wrapper");

    let content = fs::read_to_string(output_dir.join("battle/view/sparse.view.ron"))
        .expect("generated file should be readable");
    assert!(
        !content.contains("2000-01-01 00:00:00 +00:00"),
        "timestamp should refresh"
    );
    assert!(
        content.contains("tags: []"),
        "new output should include all fields (text-based comparison in vessel)"
    );
    assert!(
        content.contains("name: \"Root\""),
        "existing semantic content should remain"
    );

    let _ = fs::remove_dir_all(&output_dir);
}
