[package]
name = "souprune"
version = "0.3.0"
edition = "2024"
authors = ["Bli-AIk <haikun2333@gmail.com>"]
license = "LGPL-3.0-or-later"
repository = "https://github.com/Bli-AIk/souprune"
homepage = "https://github.com/Bli-AIk/souprune"
description = "A game framework designed specifically for Deltarune / Undertale fangames."
documentation = "https://docs.rs/souprune"
readme = "../../readme.md"
keywords = ["game-framework", "deltarune", "undertale", "game-engine", "bevy"]
categories = ["game-development", "game-engines"]

[dependencies]
bevy = { version = "0.17.2", default-features = false, features = [
    "bevy_animation",
    "bevy_asset",
    "bevy_color",
    "bevy_core_pipeline",
    "bevy_gilrs",
    "bevy_gizmos",
    "bevy_gltf",
    "bevy_pbr",
    "bevy_picking",
    "bevy_render",
    "bevy_scene",
    "bevy_sprite",
    "bevy_state",
    "bevy_text",
    "bevy_ui",
    "bevy_winit",
    "file_watcher",
    "multi_threaded",
    "png",
    "x11",
    "wayland",
] }
leafwing-input-manager = "0.19.0"
seldom_state = "0.15.0"
bevy_ecs_tiled = { git = "https://github.com/adrien-bon/bevy_ecs_tiled.git", branch = "dev" }
bevy_tween = "0.10.0"
bevy_ecs_typewriter = { path = "../bevy_ecs_typewriter" }
bevy_fact_rule_event = { path = "../bevy_fact_rule_event" }
bevy_mortar_bond = { path = "../bevy_mortar_bond" }
log = { version = "0.4", features = ["max_level_debug", "release_max_level_warn"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ron = "0.10"
toml = "0.9.8"
bevy_smud = "0.12.0"
bevy_rich_text3d = { version = "0.5.1", features = ["reflect"] }
bevy_kira_audio = { version = "0.24", features = ["wav", "ogg", "flac", "mp3"] }
anyhow = "1.0.100"
tracing-appender = "0.2.4"
tracing-subscriber = "0.3.22"
tracing = "0.1.43"
chrono = "0.4.42"
evalexpr = "13.1.0"
proptest = "1.9.0"

[dev-dependencies]
once_cell = "1.20.2"
walkdir = "2.5.0"

[dependencies.bevy-inspector-egui]
version = "0.35.0"
optional = true

[dependencies.iyes_perf_ui]
git = "https://github.com/Bli-AIk/iyes_perf_ui"
branch = "bevy-0.17"
optional = true

[features]
default = []
debug = ["dep:bevy-inspector-egui", "dep:iyes_perf_ui"]
