//! Guest-side helpers for Vessel content modules.
//!
//! Vessel 内容模块的 guest 侧辅助工具。

use anyhow::Result;
use serde::Serialize;

wit_bindgen::generate!({
    path: "../vessel/wit",
    world: "content-module",
    pub_export_macro: true,
});

/// Re-exports of generated WIT guest-side items.
///
/// WIT guest 侧生成项的重导出。
pub mod wit {
    pub use super::Guest;
    pub use super::export;
    pub use super::vessel::build::types::GeneratedFile;
}

/// Guest-side registry that collects generated RON files before export.
///
/// guest 侧注册表，用于在导出前收集生成的 RON 文件。
#[derive(Default)]
pub struct Registry {
    files: Vec<wit::GeneratedFile>,
}

impl Registry {
    pub fn new() -> Self {
        Self::default()
    }

    /// Emit a serializable value as pretty-printed RON.
    ///
    /// 将一个可序列化值发射为格式化 RON。
    pub fn emit_ron<T: Serialize>(&mut self, path: impl Into<String>, value: &T) -> Result<()> {
        let config = ron::ser::PrettyConfig::default()
            .struct_names(true)
            .enumerate_arrays(false);
        let ron_str = ron::ser::to_string_pretty(value, config)?;
        self.files.push(wit::GeneratedFile {
            path: path.into(),
            ron_text: format!("// Generated by Vessel — do not edit manually\n{ron_str}\n"),
        });
        Ok(())
    }

    pub fn into_generated_files(self) -> Vec<wit::GeneratedFile> {
        self.files
    }
}
