//! # chapter.rs
//!
//! # chapter.rs 文件
//!
//! ## Module Overview
//!
//! ## 模块概述
//!
//! Chapter is the minimal unit of the linear sequence in the battle system.
//! It is an enum type representing different events in the battle.
//! For example, player choices, bullet pattern generation, dialogues, and nested Chapters.
//! Chapter itself does not contain definitions or implementations of bullet patterns or UI.
//!
//! Chapter 是 战斗系统中线性序列的最小单位。
//! 它是一个枚举类型，表示战斗中的不同事件。
//! 例如，玩家选择、弹幕生成、对话、以及 Chapter 的嵌套等。
//! Chapter 本身不包含 弹幕 或 UI 的定义与具体实现。

use bevy::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Deserialize, Serialize)]
pub enum Chapter {
    /// UI Interaction Chapter.
    ///
    /// The Chapter allows players to interact with the UI.
    /// Chapters involving UI interaction should apply this, such as player choices, dialogues, etc.
    ///
    /// UI 交互章节。
    ///
    /// 此章节允许玩家与 UI 交互。
    /// 涉及 UI 交互的章节都应应用此项，如 玩家选择、对话 等。
    UIInteraction { ui_layout: String },

    /// Bullet Pattern Chapter.
    ///
    /// The Chapter is responsible for generating bullet patterns.
    ///
    /// 弹幕生成章节。
    ///
    /// 此章节负责生成弹幕模式。
    BulletPattern {
        pattern_id: Vec<String>,
        // TODO: 我们需要评估是否需要在这里添加更多的参数，例如 击破条件、name、时间限制 等。
    },

    /// Simple Wait Chapter.
    ///
    /// 简单的等待章节。
    Wait(f32),

    /// Nested Chapter.
    ///
    /// 章节的嵌套。
    Nested(Vec<Chapter>),

    /// Set Player State Chapter.
    /// Please note that in Battle, a player entity is not generated by default.
    /// If a player entity is needed to participate in the battle chapter,
    /// it must be generated through this chapter.
    ///
    /// 设置玩家状态的章节。
    /// 请注意，Battle 中，默认不会生成一个玩家实体。
    /// 如果需要玩家实体参与战斗章节，必须通过此章节进行生成。
    SetPlayer(PlayerAction),
}

/// Player Action Enum.
///
/// 操作玩家的一系列枚举项。
#[derive(Debug, Clone, Deserialize, Serialize)]
pub enum PlayerAction {
    /// Set Mode for the player.
    /// Mode refers to different behavioral states defined in the Character Asset,
    /// such as "movable", "jumpable", "shootable", etc.
    /// The String references the mode names defined in the Character Asset.
    ///
    /// 设置玩家的模式。
    /// 模式 即 角色资产 中定义的 不同行为状态。
    /// 如“可移动”、“可跳跃”、“可射击”等。
    /// String 引用的是 角色资产 中定义的 模式 名称。
    SetMode(Vec<String>),

    /// Teleport the player to a specified position.
    ///
    /// 将玩家传送到指定位置。
    Teleport(Vec2),

    /// Set the active state of the player.
    ///
    /// 设置玩家的激活状态。
    SetActive(bool),

    /// Despawn the player entity.
    ///
    /// 销毁玩家实体。
    Despawn,
}
