name = "example_battle_mod"
version = "0.1.0"
authors = ["Your Name"]
description = "An example mod for SoupRune (Battle Only)."

[dependencies]
# List dependencies here

[soul_modes]
# These IDs are now all provided by the same DLL below
"soul_red" = "libexample_battle_mod.so"
"soul_blue" = "libexample_battle_mod.so"

[game]
initial_battle_path = "battle/chapters/demo.battle.ron"
input_config_path = "config/input.ron"
required_modules = ["common", "battle"]
